// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEWxWI6pwijVm90HTfW2bq4st5hMsB8RM',
    appId: '1:412261858786:web:f97ae7e706bb2b44b5cdbb',
    messagingSenderId: '412261858786',
    projectId: 'kart-3dbcc',
    authDomain: 'kart-3dbcc.firebaseapp.com',
    storageBucket: 'kart-3dbcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3c2DwazhD7UgPA3IHYAIaylSvqcAAqc',
    appId: '1:412261858786:android:6479b3966146dfdbb5cdbb',
    messagingSenderId: '412261858786',
    projectId: 'kart-3dbcc',
    storageBucket: 'kart-3dbcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNQ1jMDOBdj2vDPtc86EJvMSIYAknjqxc',
    appId: '1:412261858786:ios:0c65eb8c0ab8d894b5cdbb',
    messagingSenderId: '412261858786',
    projectId: 'kart-3dbcc',
    storageBucket: 'kart-3dbcc.appspot.com',
    iosClientId:
        '412261858786-iomr7b97e38p4gpbigl0jr5han90uo3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.kart2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNQ1jMDOBdj2vDPtc86EJvMSIYAknjqxc',
    appId: '1:412261858786:ios:0c65eb8c0ab8d894b5cdbb',
    messagingSenderId: '412261858786',
    projectId: 'kart-3dbcc',
    storageBucket: 'kart-3dbcc.appspot.com',
    iosClientId:
        '412261858786-iomr7b97e38p4gpbigl0jr5han90uo3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.kart2',
  );
}
